# Generated by Django 4.2.4 on 2023-10-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_date',
            new_name='post_date',
        ),
    ]
